<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $book_data = [
            [
                'title' => 'The Great Escape',
                'author' => 'John Smith',
                'publication_year' => 2015,
                'genre_id' => '1',
                'rating' => 4.2,
                'price' => 12.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Art of War',
                'author' => 'Sun Tzu',
                'publication_year' => 500,
                'genre_id' => '2',
                'rating' => 4.8,
                'price' => 9.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'publication_year' => 1813,
                'genre_id' => '3',
                'rating' => 4.5,
                'price' => 14.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'publication_year' => 1960,
                'genre_id' => '4',
                'rating' => 4.7,
                'price' => 11.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Lord of the Rings',
                'author' => 'J.R.R. Tolkien',
                'publication_year' => 1954,
                'genre_id' => '5',
                'rating' => 4.9,
                'price' => 19.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'publication_year' => 1949,
                'genre_id' => '6',
                'rating' => 4.6,
                'price' => 13.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'publication_year' => 1951,
                'genre_id' => '7',
                'rating' => 4.3,
                'price' => 10.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'publication_year' => 1997,
                'genre_id' => '5',
                'rating' => 4.8,
                'price' => 15.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'publication_year' => 1937,
                'genre_id' => '5',
                'rating' => 4.7,
                'price' => 14.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'publication_year' => 2003,
                'genre_id' => '8',
                'rating' => 4.1,
                'price' => 12.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'publication_year' => 1925,
                'genre_id' => '4',
                'rating' => 4.5,
                'price' => 11.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'publication_year' => 1988,
                'genre_id' => '5',
                'rating' => 4.4,
                'price' => 9.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Moby-Dick',
                'author' => 'Herman Melville',
                'publication_year' => 1851,
                'genre_id' => '9',
                'rating' => 4.3,
                'price' => 12.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Chronicles of Narnia',
                'author' => 'C.S. Lewis',
                'publication_year' => 1950,
                'genre_id' => '5',
                'rating' => 4.6,
                'price' => 18.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Odyssey',
                'author' => 'Homer',
                'publication_year' => 800,
                'genre_id' => '10',
                'rating' => 4.7,
                'price' => 13.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'A Game of Thrones',
                'author' => 'George R.R. Martin',
                'publication_year' => 1996,
                'genre_id' => '5',
                'rating' => 4.9,
                'price' => 16.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Divine Comedy',
                'author' => 'Dante Alighieri',
                'publication_year' => 1320,
                'genre_id' => '11',
                'rating' => 4.6,
                'price' => 11.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Jane Eyre',
                'author' => 'Charlotte Brontë',
                'publication_year' => 1847,
                'genre_id' => '3',
                'rating' => 4.4,
                'price' => 10.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Girl with the Dragon Tattoo',
                'author' => 'Stieg Larsson',
                'publication_year' => 2005,
                'genre_id' => '8',
                'rating' => 4.2,
                'price' => 14.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Shining',
                'author' => 'Stephen King',
                'publication_year' => 1977,
                'genre_id' => '12',
                'rating' => 4.3,
                'price' => 12.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Picture of Dorian Gray',
                'author' => 'Oscar Wilde',
                'publication_year' => 1890,
                'genre_id' => '13',
                'rating' => 4.1,
                'price' => 9.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Brave New World',
                'author' => 'Aldous Huxley',
                'publication_year' => 1932,
                'genre_id' => '6',
                'rating' => 4.4,
                'price' => 11.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Hitchhiker\'s Guide to the Galaxy',
                'author' => 'Douglas Adams',
                'publication_year' => 1979,
                'genre_id' => '14',
                'rating' => 4.5,
                'price' => 13.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Crime and Punishment',
                'author' => 'Fyodor Dostoevsky',
                'publication_year' => 1866,
                'genre_id' => '15',
                'rating' => 4.6,
                'price' => 14.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Gone with the Wind',
                'author' => 'Margaret Mitchell',
                'publication_year' => 1936,
                'genre_id' => '16',
                'rating' => 4.3,
                'price' => 12.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'publication_year' => 2008,
                'genre_id' => '6',
                'rating' => 4.7,
                'price' => 15.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Book Thief',
                'author' => 'Markus Zusak',
                'publication_year' => 2005,
                'genre_id' => '16',
                'rating' => 4.5,
                'price' => 10.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Count of Monte Cristo',
                'author' => 'Alexandre Dumas',
                'publication_year' => 1844,
                'genre_id' => '9',
                'rating' => 4.7,
                'price' => 13.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Kite Runner',
                'author' => 'Khaled Hosseini',
                'publication_year' => 2003,
                'genre_id' => '16',
                'rating' => 4.6,
                'price' => 11.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'The Secret Garden',
                'author' => 'Frances Hodgson Burnett',
                'publication_year' => 1911,
                'genre_id' => '17',
                'rating' => 4.2,
                'price' => 9.99,
                'image' => 'jane-austen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        
        
        DB::table('books')->insert($book_data);
    }
}
